### ISSUE TITLE
How to implment a correct Aob Scan with reload.memory & reload.memory.SigScan ?

### ISSUE THREAD

**Issue by MichaelVanHouHei** [Reloaded-Project/Reloaded.Memory.SigScan#10]
I wanted to implement aob scan to a remote process by reload lib , is there any example code that I can tried to implement? 
my steps is using OpenProcess GET handle->GET Regions by  VirtualQueryEx  Look for writtable | excutable -> Save Region base address and size -> using reloaded.Memory.SigScan to get the offset ->  region BaseAddress + offset

**Comment by Sewer56** [comment]
You seem to be pretty much there.

Read in the regions you obtained VirtualQueryEx using `Reloaded.Memory`, like the way it is done here.

https://github.com/Reloaded-Project/Reloaded.Memory.SigScan/blob/35063d046c975b9832a9ddb3f3d50cebce152c0a/Reloaded.Memory.Sigscan/Scanner.cs#L70-L75

And pass the pointer and length to the constructor as needed.

Just be aware, length is limited to 2GiB; I built this thing to originally scan code in EXE files only.
