### ISSUE TITLE
`System.Runtime.CompilerServices.Unsafe` Version Mismatch.

### ISSUE THREAD

**Issue by Razmoth** [Reloaded-Project/Reloaded.Memory.SigScan#5]
Greetings.

While using `SigScan v3.0.1`, It asks for `System.Runtime.CompilerServices.Unsafe v4.5.3`, my project already has reference to  `System.Runtime.CompilerServices.Unsafe v5.0.0`, and `SigScan` library requires `>= v4.7.0` according to `NuGet` description.

![image](https://user-images.githubusercontent.com/32140579/174993263-c341cef3-e906-4100-bf99-902437757dfb.png)

![image](https://user-images.githubusercontent.com/32140579/174994591-0cc2aa28-abe0-4f4e-bdf2-79abff1b9db5.png)

![image](https://user-images.githubusercontent.com/32140579/174994051-3acf2e29-9845-450e-a5d8-613a110099d2.png)

![image](https://user-images.githubusercontent.com/32140579/174994978-ba1f2249-ce10-4b65-885a-08671cdebd78.png)

Thanks in advance.

**Comment by Sewer56** [comment]
Which TFM (Target Framework) is your application targeting?

I'll check quickly if it's a config issue.

**Comment by Razmoth** [comment]
NET Framework v4.7.2

**Comment by Sewer56** [comment]
I've tried reproducing this in a clean new project however I've come up short.

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>NET472</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Reloaded.Memory.Sigscan" Version="3.0.1" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="5.0.0" />
  </ItemGroup>

</Project>
```

```csharp
// Dummy code
var code = new byte[12321];
var scanner = new Scanner(code);
scanner.FindPattern("00 FF 00");
```

Would you happen to be using the old `.csproj` format and/or `packages.config`?
If so, [this might be able to help](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection#enable-automatic-binding-redirects-manually).

Deleting the `obj` folders (or just doing a rebuild) might help too.

**Comment by Razmoth** [comment]
It's definitely related to binding redirect.

However, the issue is that the executable project will invoke a function from another `Class Library` project, which does not have `app.config`, trying to add it manually doesn't seem to help as well.

![Project Used](https://github.com/DaZombieKiller/TypeTreeDumper/tree/2fe376e03c0aceb1cc1f2274b7f577f883c58533).

Apologize for explaining it poorly, but essentially there are 3 project (excluding `Loader`), 2 libraries 1 executable, the `Bootstrapper` will invoke a function from `TypeTreeDumper`, The `TypeTreeDumper` has the reference to `SigScan` and a dependency to `Unity`, of which it has the reference to `System.Runtime.CompilerServices.Unsafe v5.0.0`.

`Inject Code`:
![image](https://user-images.githubusercontent.com/32140579/175009380-bedaaa53-2fdf-4775-91e1-dfc146f0485a.png)

`TypeTreeDumper.Bootstrapper.exe.config:`
![image](https://user-images.githubusercontent.com/32140579/175009016-e881a660-3fa1-4a41-b197-e84dc60bbb10.png)

![image](https://user-images.githubusercontent.com/32140579/175008125-7933c738-425e-4cd8-87de-dd53685466ab.png)

![image](https://user-images.githubusercontent.com/32140579/175008533-19108fb9-db00-4d65-b610-cda8e2108517.png)

![image](https://user-images.githubusercontent.com/32140579/175008102-5bd4669e-d5b5-4429-9ce7-970233b95065.png)

![image](https://user-images.githubusercontent.com/32140579/175008657-e18e060c-91f0-4014-a8a4-ff3c5d89a81b.png)

If you don't mind, I can share the project files to test it out, I'd really appreciate it.

Thanks.

**Comment by Sewer56** [comment]
Feel free, albeit I'd probably be troubleshooting in the exact same way that you are.  
It's been a pretty long time since I've used Framework.  

The initial screenshot with the stack trace errored at `Span<T>` which makes me think this could also potentially be related to `System.Memory`.

**Comment by Razmoth** [comment]
Guessed it right !! it was indeed `System.Memory` call, weird that `PrivatePath` is null despite it being set in `TypeTreeDumper.Bootstrapper.exe.config`.

![image](https://user-images.githubusercontent.com/32140579/175019742-4cc9df97-7fe9-47e9-91a6-7b18a8136190.png)

**Comment by Razmoth** [comment]
I believe this is no longer an issue related with `SigScan`. will look into it on my own.

Thank you for the help

**Comment by Sewer56** [comment]
No sweat, have fun and good luck.
